# Generated by Django 5.2.4 on 2025-08-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogie_no', models.CharField(max_length=50, verbose_name='Bogie No.')),
                ('date_of_ioh', models.DateField(blank=True, null=True, verbose_name='Date of IOH')),
                ('incoming_div_and_date', models.CharField(max_length=100, verbose_name='Incoming Div. & Date')),
                ('maker_year_built', models.CharField(max_length=100, verbose_name='Maker & Year Built')),
                ('deficit_components', models.TextField(blank=True, null=True, verbose_name='Deficit of component (if any)')),
                ('bogie_frame_condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bogie Frame Condition')),
                ('bolster', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bolster')),
                ('bolster_suspension_bracket', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bolster Suspension Bracket')),
                ('lower_spring_seat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lower Spring Seat')),
                ('axle_guide', models.CharField(blank=True, max_length=50, null=True, verbose_name='Axle Guide')),
                ('axle_guide_assembly', models.CharField(blank=True, max_length=50, null=True, verbose_name='Axle Guide Assembly')),
                ('protective_tubes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Protective Tubes')),
                ('anchor_links', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anchor Links')),
                ('side_bearer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Side Bearer')),
                ('cylinder_body', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cylinder Body & Dome Cover')),
                ('piston_trunnion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Piston & Trunnion Body')),
                ('adjusting_tube', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adjusting Tube and Screw')),
                ('plunger_spring', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plunger Spring')),
                ('tee_bolt_hex_nut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tee Bolt, Hex Nut')),
                ('pawl_and_pawl_spring', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pawl and Pawl Spring')),
                ('dust_excluder', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dust Excluder')),
                ('form_number', models.CharField(max_length=50)),
                ('inspection_by', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tread_diameter_new', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tread Diameter (New)')),
                ('last_shop_issue_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Shop Issue Size (Dia.)')),
                ('condemning_dia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condemning Dia.')),
                ('wheel_gauge', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wheel Gauge (IFD)')),
                ('variation_same_axle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Variation Same Axle')),
                ('variation_same_bogie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Variation Same Bogie')),
                ('variation_same_coach', models.CharField(blank=True, max_length=50, null=True, verbose_name='Variation Same Coach')),
                ('wheel_profile', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wheel Profile')),
                ('intermediate_wwp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Intermediate WWP')),
                ('bearing_seat_diameter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bearing Seat Diameter')),
                ('roller_bearing_outer_dia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Roller Bearing Outer Dia.')),
                ('roller_bearing_bore_dia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Roller Bearing Bore Dia.')),
                ('roller_bearing_width', models.CharField(blank=True, max_length=100, null=True, verbose_name='Roller Bearing Width')),
                ('axle_box_housing_bore_dia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Axle Box Housing Bore Dia.')),
                ('wheel_disc_width', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wheel Disc Width')),
                ('form_number', models.CharField(max_length=50)),
                ('submitted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
