version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sai@6303179072$
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 kpa_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Sai@6303179072$
    depends_on:
      - db
